# Generated by Django 5.2 on 2025-04-29 22:04

from django.db import migrations, models
import django.db.models.deletion


def populate_job_fields(apps, schema_editor):
    Job = apps.get_model('execution', 'Job')
    for job in Job.objects.all():
        job.job_id = f'JOB-{job.id:04d}'
        job.job_name = f'{job.job_type} job for Order {job.order.order_number}'
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_add_campaign_model'),
    ]

    operations = [
        # First add the fields as nullable
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='completion_time',
            field=models.FloatField(blank=True, help_text='Time in days which were spent to complete the job.', null=True),
        ),
        # Add the order field as nullable first
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_jobs', to='execution.order'),
        ),
        # Run the data migration
        migrations.RunPython(populate_job_fields),
        # Now make the fields required
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='execution.order'),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'job_type'], name='job_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['started_at', 'completed_at'], name='job_dates_idx'),
        ),
        # Remove the old orders field
        migrations.RemoveField(
            model_name='job',
            name='orders',
        ),
    ]
